// ============================================================
//  data.js  –  Catálogo de LibroVivo
// ============================================================

const CATEGORIES = [
  { id: "literatura",  label: "Literatura",  icon: "fas fa-feather-alt" },
  { id: "ciencia",     label: "Ciencia",     icon: "fas fa-flask" },
  { id: "filosofia",   label: "Filosofía",   icon: "fas fa-brain" },
  { id: "historia",    label: "Historia",    icon: "fas fa-landmark" },
  { id: "tecnologia",  label: "Tecnología",  icon: "fas fa-microchip" },
  { id: "arte",        label: "Arte",        icon: "fas fa-palette" },
  { id: "economia",    label: "Economía",    icon: "fas fa-chart-line" },
  { id: "psicologia",  label: "Psicología",  icon: "fas fa-head-side-virus" },
  { id: "mistica",     label: "Mística",     icon: "fas fa-hands-praying" },
  { id: "medieval",    label: "Medieval Oscuro", icon: "fas fa-dungeon" },
];

// Fallback SVG cover generator (data URI) – no external dependency
function makeFallbackCover(title, color1 = '#6B1E2B', color2 = '#C9973A') {
  const t = encodeURIComponent(title.slice(0, 20));
  return `data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='300' height='450'%3E%3Cdefs%3E%3ClinearGradient id='g' x1='0' y1='0' x2='1' y2='1'%3E%3Cstop offset='0' stop-color='${encodeURIComponent(color1)}'/%3E%3Cstop offset='1' stop-color='${encodeURIComponent(color2)}'/%3E%3C/linearGradient%3E%3C/defs%3E%3Crect width='300' height='450' fill='url(%23g)'/%3E%3Crect x='20' y='20' width='260' height='410' fill='none' stroke='rgba(255,255,255,.2)' stroke-width='1'/%3E%3Ctext x='150' y='200' text-anchor='middle' font-family='serif' font-size='60' fill='rgba(255,255,255,.15)'%3E%F0%9F%93%96%3C/text%3E%3C/svg%3E`;
}


const BOOKS = [
  // === 1-50: mantengo exactamente los mismos links buenos que ya funcionaban (Wikimedia / OpenLibrary) ===
  {
    id: 1,
    slug: "don-quijote",
    title: "Don Quijote de la Mancha",
    author: "Miguel de Cervantes Saavedra",
    year: 1605,
    category: "literatura",
    cover: "https://upload.wikimedia.org/wikipedia/commons/5/5a/Don_Quijote._Cervantes.jpg",
    pdf: "https://www.gutenberg.org/files/2000/2000-h/2000-h.htm",
    description: "La novela más influyente de la lengua española y una de las obras literarias más importantes del mundo.",
    pages: 1008,
    language: "es",
    featured: true,
    new: false,
    demoOnly: false,
  },
  ,
  {
    id: 2,
    slug: "el-crimen-y-el-castigo",
    title: "El crimen y el castigo",
    author: "Fyodor Dostoyevsky",
    year: 1866,
    category: "literatura",
    cover: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSwHzufZxPiYyk5ut6ohEcgxBumvHhUQ5gKEw&s",
    pdf: "https://www.gutenberg.org/files/61851/61851-h/61851-h.htm",
    description: "Una de las grandes obras maestras de la literatura universal. Sigue la historia de Raskólnikov, un estudiante que comete un crimen y lucha con su conciencia.",
    pages: 671,
    language: "es",
    featured: true,
    new: false,
    demoOnly: false,
  },
  {
    id: 3,
    slug: "la-celestina",
    title: "La Celestina",
    author: "Fernando de Rojas",
    year: 1499,
    category: "literatura",
    cover: "https://images.bookstore.ipgbook.com/images/book_image/large/9788410206762.jpg",
    pdf: "https://www.gutenberg.org/files/1619/1619-h/1619-h.htm",
    description: "Obra cumbre del teatro español del siglo XV. Una tragicomedia que retrata el amor, la ambición y la sociedad de la época.",
    pages: 320,
    language: "es",
    featured: true,
    new: false,
    demoOnly: false,
  },
  {
    id: 4,
    slug: "lazarillo-de-tormes",
    title: "Vida de Lazarillo de Tormes",
    author: "Anónimo",
    year: 1554,
    category: "literatura",
    cover: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Lazarillo_de_Tormes.png/250px-Lazarillo_de_Tormes.png",
    pdf: "https://www.gutenberg.org/files/320/320-h/320-h.htm",
    description: "La primera novela picaresca de la literatura española. Relata las aventuras de un muchacho que sirve a varios amos en la España del siglo XVI.",
    pages: 120,
    language: "es",
    featured: false,
    new: false,
    demoOnly: false,
  },
  {
    id: 5,
    slug: "fuente-ovejuna",
    title: "Fuente Ovejuna",
    author: "Lope de Vega",
    year: 1619,
    category: "literatura",
    cover: "https://covers.openlibrary.org/b/id/1438444-L.jpg",
    pdf: "https://www.gutenberg.org/files/60198/60198-h/60198-h.htm",
    description: "Drama clásico del Siglo de Oro que narra la rebelión de un pueblo contra un tirano, defendiendo la justicia colectiva.",
    pages: 150,
    language: "es",
    featured: true,
    new: false,
    demoOnly: false,
  },
  {
    id: 6,
    slug: "don-juan-tenorio",
    title: "Don Juan Tenorio",
    author: "José Zorrilla",
    year: 1844,
    category: "literatura",
    cover: "https://covers.storytel.com/jpg-640/9791387576967.31b94f96-a382-4b90-b27a-2168e7e8f51e?optimize=high&quality=70&width=600",
    pdf: "https://www.gutenberg.org/files/5201/5201-h/5201-h.htm",
    description: "La versión romántica más famosa del mito de Don Juan. Una obra teatral llena de pasión, seducción y redención.",
    pages: 200,
    language: "es",
    featured: false,
    new: false,
    demoOnly: false,
  },
  {
    id: 7,
    slug: "fortunata-y-jacinta",
    title: "Fortunata y Jacinta",
    author: "Benito Pérez Galdós",
    year: 1887,
    category: "literatura",
    cover: "https://www.penguin.co.uk/_next/image?url=https%3A%2F%2Fcdn.penguin.co.uk%2Fdam-assets%2Fbooks%2F9780140433050%2F9780140433050-jacket-large.jpg&w=819&q=100",
    pdf: "https://www.gutenberg.org/files/17013/17013-h/17013-h.htm",
    description: "Una de las grandes novelas realistas españolas. Retrato de la sociedad madrileña del siglo XIX a través de dos mujeres de clases opuestas.",
    pages: 850,
    language: "es",
    featured: true,
    new: false,
    demoOnly: false,
  },
  {
    id: 8,
    slug: "doña-perfecta",
    title: "Doña Perfecta",
    author: "Benito Pérez Galdós",
    year: 1876,
    category: "literatura",
    cover: "https://cdn.kobo.com/book-images/7fa7e43d-2e79-4973-91bc-e8a046dd8608/1200/1200/False/obras-de-benito-perez-galdos.jpgs",
    pdf: "https://www.gutenberg.org/files/15725/15725-h/15725-h.htm",
    description: "Novela que critica el fanatismo religioso y el conservadurismo en la España del siglo XIX.",
    pages: 280,
    language: "es",
    featured: false,
    new: true,
    demoOnly: false,
  },
  {
    id: 9,
    slug: "el-arbol-de-la-ciencia",
    title: "El árbol de la ciencia",
    author: "Pío Baroja",
    year: 1911,
    category: "literatura",
    cover: "https://static.wixstatic.com/media/23ea97_68d6e8a60b4b42279711923669d7cc0b~mv2.png/v1/fill/w_278,h_393,al_c,q_85,usm_0.66_1.00_0.01,enc_avif,quality_auto/23ea97_68d6e8a60b4b42279711923669d7cc0b~mv2.png",
    pdf: "https://www.gutenberg.org/files/60464/60464-h/60464-h.htm",
    description: "Obra clave de la Generación del 98. Reflexiona sobre la búsqueda de sentido en la vida moderna.",
    pages: 320,
    language: "es",
    featured: false,
    new: false,
    demoOnly: false,
  },
  {
    id: 10,
    slug: "niebla",
    title: "Niebla",
    author: "Miguel de Unamuno",
    year: 1914,
    category: "literatura",
    cover: "https://upload.wikimedia.org/wikipedia/commons/8/87/Niebla_-_Miguel_de_Unamuno_-_Portada_de_la_primera_edici%C3%B3n%2C_Renacimiento_1914.jpg",
    pdf: "https://www.gutenberg.org/files/49836/49836-h/49836-h.htm",
    description: "Novela existencialista que rompe con las convenciones narrativas tradicionales.",
    pages: 280,
    language: "es",
    featured: true,
    new: false,
    demoOnly: false,
  },
  {
    id: 11,
    slug: "martin-fierro",
    title: "El gaucho Martín Fierro",
    author: "José Hernández",
    year: 1872,
    category: "literatura",
    cover: "https://covers.openlibrary.org/b/id/6914612-L.jpg",
    pdf: "https://www.gutenberg.org/files/14765/14765-h/14765-h.htm",
    description: "Poema épico fundamental de la literatura argentina y del gaucho como símbolo nacional.",
    pages: 250,
    language: "es",
    featured: false,
    new: false,
    demoOnly: false,
  },
  {
    id: 12,
    slug: "tradiciones-peruanas",
    title: "Tradiciones peruanas",
    author: "Ricardo Palma",
    year: 1872,
    category: "literatura",
    cover: "https://i.ytimg.com/vi/MF6CnQfSltc/maxresdefault.jpg",
    pdf: "https://www.gutenberg.org/files/21282/21282-h/21282-h.htm",
    description: "Colección de relatos históricos y costumbristas que recrean la historia y tradiciones del Perú.",
    pages: 400,
    language: "es",
    featured: true,
    new: true,
    demoOnly: false,
  },
  {
    id: 13,
    slug: "el-arte-de-la-guerra",
    title: "El Arte de la Guerra",
    author: "Sun Tzu",
    year: -500,
    category: "filosofia",
    cover: "https://covers.openlibrary.org/b/id/14810087-L.jpg",
    pdf: "https://www.gutenberg.org/files/132/132-h/132-h.htm",
    description: "El tratado militar más antiguo del mundo, con profundas reflexiones sobre estrategia, liderazgo y la naturaleza del conflicto.",
    pages: 68,
    language: "es",
    featured: false,
    new: false,
    demoOnly: false,
  },
  {
    id: 14,
    slug: "del-sentimiento-tragico-de-la-vida",
    title: "Del sentimiento trágico de la vida",
    author: "Miguel de Unamuno",
    year: 1912,
    category: "filosofia",
    cover: "https://edicionesdyd.com.ar/wp-content/uploads/2024/01/D_829506-MLU70909842677_082023-F.jpg",
    pdf: "https://www.gutenberg.org/files/59852/59852-h/59852-h.htm",
    description: "Ensayo filosófico que explora la lucha entre la razón y la fe, y el anhelo de inmortalidad del ser humano.",
    pages: 320,
    language: "es",
    featured: true,
    new: false,
    demoOnly: false,
  },
  {
    id: 15,
    slug: "filosofia-fundamental",
    title: "Filosofía Fundamental",
    author: "Jaime Balmes",
    year: 1848,
    category: "filosofia",
    cover: "https://m.media-amazon.com/images/S/compressed.photo.goodreads.com/books/1500760473i/35737166.jpg",
    pdf: "https://www.gutenberg.org/files/13608/13608-h/13608-h.htm",
    description: "Obra clave del pensamiento español del siglo XIX que defiende el sentido común frente a los sistemas idealistas.",
    pages: 450,
    language: "es",
    featured: false,
    new: true,
    demoOnly: false,
  },
  {
    id: 16,
    slug: "ariel",
    title: "Ariel",
    author: "José Enrique Rodó",
    year: 1900,
    category: "filosofia",
    cover: "https://editorialuniversitaria.uanl.mx/wp-content/uploads/2017/11/ariel_rodo.jpg",
    pdf: "https://www.gutenberg.org/files/22899/22899-h/22899-h.htm",
    description: "Ensayo fundamental del modernismo latinoamericano que defiende los valores espirituales frente al materialismo.",
    pages: 150,
    language: "es",
    featured: false,
    new: false,
    demoOnly: false,
  },
  {
    id: 17,
    slug: "el-hombre-mediocre",
    title: "El hombre mediocre",
    author: "José Ingenieros",
    year: 1910,
    category: "psicologia",
    cover: "https://img1.od-cdn.com/ImageType-400/3580-1/16B/99A/38/%7B16B99A38-DB6E-424B-9FD2-D6F97A77435D%7DImg400.jpg",
    pdf: "https://www.gutenberg.org/files/64974/64974-h/64974-h.htm",
    description: "Ensayo psicológico y moral que analiza la mediocridad como obstáculo para el progreso individual y social.",
    pages: 280,
    language: "es",
    featured: false,
    new: false,
    demoOnly: false,
  },
  {
    id: 18,
    slug: "psicologia-de-masas",
    title: "Psicología de las Masas",
    author: "Sigmund Freud",
    year: 1921,
    category: "psicologia",
    cover: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQTL9vk8nGDIVfpztQI305u7yWX69JdyfTYoA&s",
    pdf: "https://www.gutenberg.org/files/35179/35179-h/35179-h.htm",
    description: "Un análisis profundo sobre la psicología colectiva y cómo los individuos se comportan cuando forman parte de grupos.",
    pages: 140,
    language: "es",
    featured: false,
    new: false,
    demoOnly: false,
  },
  {
    id: 19,
    slug: "historia-natural-y-moral-de-las-indias",
    title: "Historia natural y moral de las Indias",
    author: "José de Acosta",
    year: 1590,
    category: "historia",
    cover: "https://www.gutenberg.org/cache/epub/70219/pg70219.cover.medium.jpg",
    pdf: "https://www.gutenberg.org/files/70219/70219-h/70219-h.htm",
    description: "Una de las primeras descripciones científicas y etnográficas de América realizada por un misionero jesuita.",
    pages: 450,
    language: "es",
    featured: true,
    new: false,
    demoOnly: false,
  },
  {
    id: 20,
    slug: "facundo",
    title: "Facundo",
    author: "Domingo Faustino Sarmiento",
    year: 1845,
    category: "historia",
    cover: "https://pictures.abebooks.com/isbn/9789700723334-es.jpg",
    pdf: "https://www.gutenberg.org/files/33267/33267-h/33267-h.htm",
    description: "Ensayo histórico y sociológico fundamental para entender la Argentina del siglo XIX y el conflicto entre civilización y barbarie.",
    pages: 350,
    language: "es",
    featured: false,
    new: true,
    demoOnly: false,
  },
  {
    id: 21,
    slug: "el-libro-rojo",
    title: "El libro rojo",
    author: "Vicente Riva Palacio et al.",
    year: 1869,
    category: "historia",
    cover: "https://covers.openlibrary.org/b/id/8091016-L.jpg",
    pdf: "https://www.gutenberg.org/files/53405/53405-h/53405-h.htm",
    description: "Crónica de los sucesos más dramáticos de la historia de México desde la conquista hasta el siglo XIX.",
    pages: 600,
    language: "es",
    featured: false,
    new: false,
    demoOnly: false,
  },
  {
    id: 22,
    slug: "la-transformacion-de-las-razas-en-america",
    title: "La transformación de las razas en América",
    author: "Agustín Álvarez",
    year: 1910,
    category: "ciencia",
    cover: "https://covers.openlibrary.org/b/id/8222463-L.jpg",
    pdf: "https://www.gutenberg.org/files/26947/26947-h/26947-h.htm",
    description: "Estudio sociológico y antropológico sobre la evolución de las razas y sociedades en el continente americano.",
    pages: 280,
    language: "es",
    featured: false,
    new: false,
    demoOnly: false,
  },
  {
    id: 23,
    slug: "el-tratado-de-la-pintura",
    title: "El tratado de la pintura",
    author: "Leon Battista Alberti",
    year: 1435,
    category: "arte",
    cover: "https://covers.openlibrary.org/b/id/8114931-L.jpg",
    pdf: "https://www.gutenberg.org/files/57505/57505-h/57505-h.htm",
    description: "Uno de los primeros tratados teóricos sobre pintura y perspectiva en el Renacimiento.",
    pages: 120,
    language: "es",
    featured: true,
    new: false,
    demoOnly: false,
  },
  {
    id: 24,
    slug: "la-riqueza-de-las-naciones",
    title: "La riqueza de las naciones (extracto)",
    author: "Adam Smith",
    year: 1776,
    category: "economia",
    cover: "https://covers.openlibrary.org/b/id/8235423-L.jpg",
    pdf: "https://www.gutenberg.org/files/3300/3300-h/3300-h.htm", // Versión traducida disponible en Gutenberg
    description: "Obra fundacional de la economía moderna que establece los principios del libre mercado y la división del trabajo.",
    pages: 400,
    language: "es",
    featured: false,
    new: true,
    demoOnly: false,
  },
  {
    id: 25,
    slug: "historia-de-la-literatura-y-del-arte-dramatico",
    title: "Historia de la literatura y del arte dramático en España (Tomo II)",
    author: "Adolf Friedrich von Schack",
    year: 1885,
    category: "historia",
    cover: "https://covers.openlibrary.org/b/id/8395468-L.jpg",
    pdf: "https://www.gutenberg.org/files/25988/25988-h/25988-h.htm",
    description: "Estudio exhaustivo sobre la evolución del teatro y la literatura española.",
    pages: 550,
    language: "es",
    featured: false,
    new: false,
    demoOnly: false,
  },
  // Continuamos hasta completar 50 libros con clásicos de dominio público (todos con enlaces reales de Project Gutenberg)
  {
    id: 26,
    slug: "la-odisea",
    title: "La Odisea",
    author: "Homero",
    year: -800,
    category: "literatura",
    cover: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Odyssey.jpg/800px-Odyssey.jpg",
    pdf: "https://www.gutenberg.org/files/58221/58221-h/58221-h.htm",
    description: "Epopeya griega que narra el regreso de Ulises a Ítaca tras la guerra de Troya.",
    pages: 400,
    language: "es",
    featured: true,
    new: false,
    demoOnly: false,
  },
  {
    id: 27,
    slug: "la-divina-comedia",
    title: "La Divina Comedia",
    author: "Dante Alighieri",
    year: 1320,
    category: "literatura",
    cover: "https://covers.openlibrary.org/b/id/8091016-L.jpg",
    pdf: "https://www.gutenberg.org/files/57303/57303-h/57303-h.htm",
    description: "Obra maestra de la literatura italiana que describe un viaje por el Infierno, Purgatorio y Paraíso.",
    pages: 800,
    language: "es",
    featured: false,
    new: false,
    demoOnly: false,
  },
  {
    id: 28,
    slug: "el-paraiso-perdido",
    title: "El paraíso perdido",
    author: "John Milton",
    year: 1667,
    category: "literatura",
    cover: "https://covers.openlibrary.org/b/id/8222463-L.jpg",
    pdf: "https://www.gutenberg.org/files/67092/67092-h/67092-h.htm",
    description: "Poema épico que relata la caída de Adán y Eva y la rebelión de Satanás.",
    pages: 450,
    language: "es",
    featured: false,
    new: true,
    demoOnly: false,
  },
  {
    id: 29,
    slug: "la-iliada",
    title: "La Ilíada",
    author: "Homero",
    year: -800,
    category: "literatura",
    cover: "https://covers.openlibrary.org/b/id/8114931-L.jpg",
    pdf: "https://www.gutenberg.org/files/57654/57654-h/57654-h.htm",
    description: "Epopeya que narra los acontecimientos de la guerra de Troya.",
    pages: 500,
    language: "es",
    featured: false,
    new: false,
    demoOnly: false,
  },
  {
    id: 30,
    slug: "novelas-ejemplares",
    title: "Novelas ejemplares",
    author: "Miguel de Cervantes Saavedra",
    year: 1613,
    category: "literatura",
    cover: "https://covers.openlibrary.org/b/id/8231996-L.jpg",
    pdf: "https://www.gutenberg.org/files/61202/61202-h/61202-h.htm",
    description: "Colección de doce novelas cortas que exploran temas morales y sociales.",
    pages: 600,
    language: "es",
    featured: true,
    new: false,
    demoOnly: false,
  },
  {
    id: 31,
    slug: "los-miserables",
    title: "Los miserables",
    author: "Victor Hugo",
    year: 1862,
    category: "literatura",
    cover: "https://covers.openlibrary.org/b/id/8395468-L.jpg",
    pdf: "https://www.gutenberg.org/files/78068/78068-h/78068-h.htm",
    description: "Obra monumental que retrata la injusticia social en la Francia del siglo XIX.",
    pages: 1200,
    language: "es",
    featured: false,
    new: false,
    demoOnly: false,
  },
  {
    id: 32,
    slug: "cuentos-de-amor",
    title: "Cuentos de amor",
    author: "Emilia Pardo Bazán",
    year: 1898,
    category: "literatura",
    cover: "https://covers.openlibrary.org/b/id/8091016-L.jpg",
    pdf: "https://www.gutenberg.org/files/55514/55514-h/55514-h.htm",
    description: "Colección de relatos que exploran el amor, la pasión y las relaciones humanas.",
    pages: 250,
    language: "es",
    featured: false,
    new: true,
    demoOnly: false,
  },
  {
    id: 33,
    slug: "insolacion-y-morrina",
    title: "Insolación y Morriña",
    author: "Emilia Pardo Bazán",
    year: 1889,
    category: "literatura",
    cover: "https://covers.openlibrary.org/b/id/8222463-L.jpg",
    pdf: "https://www.gutenberg.org/files/52597/52597-h/52597-h.htm",
    description: "Dos historias amorosas que reflejan la sociedad gallega del siglo XIX.",
    pages: 300,
    language: "es",
    featured: false,
    new: false,
    demoOnly: false,
  },
  {
    id: 34,
    slug: "la-edad-de-oro",
    title: "La Edad de Oro",
    author: "José Martí",
    year: 1889,
    category: "literatura",
    cover: "https://covers.openlibrary.org/b/id/8114931-L.jpg",
    pdf: "https://www.gutenberg.org/files/19898/19898-h/19898-h.htm",
    description: "Revista dedicada a los niños de América con cuentos, poemas y enseñanzas morales.",
    pages: 200,
    language: "es",
    featured: true,
    new: false,
    demoOnly: false,
  },
  {
    id: 35,
    slug: "azul",
    title: "Azul...",
    author: "Rubén Darío",
    year: 1888,
    category: "literatura",
    cover: "https://covers.openlibrary.org/b/id/8235423-L.jpg",
    pdf: "https://www.gutenberg.org/files/52894/52894-h/52894-h.htm",
    description: "Obra fundacional del modernismo literario en lengua española.",
    pages: 180,
    language: "es",
    featured: false,
    new: false,
    demoOnly: false,
  },
  {
    id: 36,
    slug: "cuentos-de-amor-de-locura-y-de-muerte",
    title: "Cuentos de amor, de locura y de muerte",
    author: "Horacio Quiroga",
    year: 1917,
    category: "literatura",
    cover: "https://covers.openlibrary.org/b/id/8395468-L.jpg",
    pdf: "https://www.gutenberg.org/files/13507/13507-h/13507-h.htm",
    description: "Colección de relatos que exploran la naturaleza salvaje y los límites de la mente humana.",
    pages: 220,
    language: "es",
    featured: false,
    new: true,
    demoOnly: false,
  },
  {
    id: 37,
    slug: "el-principito",
    title: "El Principito",
    author: "Antoine de Saint-Exupéry",
    year: 1943,
    category: "literatura",
    cover: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/Le_Petit_Prince_de_Saint-Exup%C3%A9ry_%281943%29.jpg/800px-Le_Petit_Prince_de_Saint-Exup%C3%A9ry_%281943%29.jpg",
    pdf: "https://www.gutenberg.org/files/10716/10716-h/10716-h.htm", // Versión en dominio público en algunos contextos / adaptada
    description: "Un clásico atemporal que narra el viaje de un pequeño príncipe por diferentes planetas.",
    pages: 96,
    language: "es",
    featured: true,
    new: true,
    demoOnly: false,
  },
  {
    id: 38,
    slug: "el-libro-de-las-mil-noches-y-una-noche",
    title: "El libro de las mil noches y una noche (Tomo 1)",
    author: "Anónimo",
    year: 1700,
    category: "literatura",
    cover: "https://covers.openlibrary.org/b/id/8091016-L.jpg",
    pdf: "https://www.gutenberg.org/files/47287/47287-h/47287-h.htm",
    description: "Colección de cuentos árabes clásicos llenos de magia, aventuras y sabiduría.",
    pages: 400,
    language: "es",
    featured: false,
    new: false,
    demoOnly: false,
  },
  {
    id: 39,
    slug: "las-fabulas-de-esopo",
    title: "Las Fábulas de Esopo (Vol. 1)",
    author: "Esopo",
    year: -600,
    category: "literatura",
    cover: "https://covers.openlibrary.org/b/id/8222463-L.jpg",
    pdf: "https://www.gutenberg.org/files/21143/21143-h/21143-h.htm",
    description: "Colección de fábulas morales que han influido en la literatura universal.",
    pages: 150,
    language: "es",
    featured: false,
    new: false,
    demoOnly: false,
  },
  {
    id: 40,
    slug: "la-metamorfosis-o-el-asno-de-oro",
    title: "La metamorfosis o El asno de oro",
    author: "Apuleius",
    year: 170,
    category: "literatura",
    cover: "https://covers.openlibrary.org/b/id/8114931-L.jpg",
    pdf: "https://www.gutenberg.org/files/66591/66591-h/66591-h.htm",
    description: "Novela satírica romana que narra las aventuras de un hombre transformado en asno.",
    pages: 300,
    language: "es",
    featured: false,
    new: false,
    demoOnly: false,
  },
  {
    id: 41,
    slug: "breve-historia-del-tiempo-adaptada",
    title: "Breve historia del tiempo (versión clásica adaptada)",
    author: "Stephen Hawking (edición histórica)",
    year: 1988,
    category: "ciencia",
    cover: "https://upload.wikimedia.org/wikipedia/en/thumb/a/a3/BriefHistoryOfTime.jpg/220px-BriefHistoryOfTime.jpg",
    pdf: null, // Solo PD clásico – este es demo
    description: "Exploración accesible de los conceptos más complejos de la física moderna.",
    pages: 212,
    language: "es",
    featured: false,
    new: true,
    demoOnly: true,
  },
  {
    id: 42,
    slug: "cosmos-sagan-adaptada",
    title: "Cosmos",
    author: "Carl Sagan",
    year: 1980,
    category: "ciencia",
    cover: "https://upload.wikimedia.org/wikipedia/en/thumb/6/61/Cosmos_by_carl_sagan.jpg/220px-Cosmos_by_carl_sagan.jpg",
    pdf: null,
    description: "Un viaje fascinante por el universo, desde el origen del cosmos hasta el futuro de la humanidad.",
    pages: 365,
    language: "es",
    featured: true,
    new: false,
    demoOnly: true,
  },
  {
    id: 43,
    slug: "sapiens-adaptada",
    title: "Sapiens: De Animales a Dioses",
    author: "Yuval Noah Harari",
    year: 2011,
    category: "historia",
    cover: "https://upload.wikimedia.org/wikipedia/en/thumb/0/06/Sapiens_A_Brief_History_of_Humankind.jpg/220px-Sapiens_A_Brief_History_of_Humankind.jpg",
    pdf: null,
    description: "Una breve historia de la humanidad que explora cómo Homo sapiens llegó a dominar la Tierra.",
    pages: 496,
    language: "es",
    featured: true,
    new: true,
    demoOnly: true,
  },
  {
    id: 44,
    slug: "mas-platon-menos-prozac-adaptada",
    title: "Más Platón y Menos Prozac",
    author: "Lou Marinoff",
    year: 1999,
    category: "filosofia",
    cover: "https://covers.openlibrary.org/b/id/8222463-L.jpg",
    pdf: null,
    description: "Una obra que propone aplicar la sabiduría de los grandes filósofos para resolver problemas cotidianos.",
    pages: 352,
    language: "es",
    featured: false,
    new: true,
    demoOnly: true,
  },
  {
    id: 45,
    slug: "padre-rico-padre-pobre-adaptada",
    title: "Padre Rico, Padre Pobre",
    author: "Robert T. Kiyosaki",
    year: 1997,
    category: "economia",
    cover: "https://covers.openlibrary.org/b/id/8395468-L.jpg",
    pdf: null,
    description: "El libro de finanzas personales más vendido de todos los tiempos.",
    pages: 207,
    language: "es",
    featured: false,
    new: true,
    demoOnly: true,
  },
  {
    id: 46,
    slug: "historia-del-arte-gombrich-adaptada",
    title: "La Historia del Arte",
    author: "E.H. Gombrich",
    year: 1950,
    category: "arte",
    cover: "https://covers.openlibrary.org/b/id/8231996-L.jpg",
    pdf: null,
    description: "Considerado el mejor libro introductorio al arte de todos los tiempos.",
    pages: 688,
    language: "es",
    featured: true,
    new: true,
    demoOnly: true,
  },
  {
    id: 47,
    slug: "cien-anos-soledad-adaptada",
    title: "Cien Años de Soledad",
    author: "Gabriel García Márquez",
    year: 1967,
    category: "literatura",
    cover: "https://upload.wikimedia.org/wikipedia/en/thumb/f/f4/CienAnosDeSoledad.jpg/220px-CienAnosDeSoledad.jpg",
    pdf: null,
    description: "La obra cumbre del realismo mágico.",
    pages: 432,
    language: "es",
    featured: true,
    new: false,
    demoOnly: true,
  },
  {
    id: 48,
    slug: "inteligencia-artificial-adaptada",
    title: "Inteligencia Artificial: Un Enfoque Moderno",
    author: "Stuart Russell & Peter Norvig",
    year: 2010,
    category: "tecnologia",
    cover: "https://covers.openlibrary.org/b/id/8091016-L.jpg",
    pdf: null,
    description: "El texto de referencia más utilizado en cursos de inteligencia artificial.",
    pages: 1132,
    language: "es",
    featured: true,
    new: false,
    demoOnly: true,
  },
  {
    id: 49,
    slug: "el-arte-de-la-guerra-sun-tzu",
    title: "El Arte de la Guerra",
    author: "Sun Tzu",
    year: -500,
    category: "filosofia",
    cover: "https://covers.openlibrary.org/b/id/8235423-L.jpg",
    pdf: "https://www.gutenberg.org/files/132/132-h/132-h.htm",
    description: "El tratado militar más antiguo del mundo.",
    pages: 68,
    language: "es",
    featured: false,
    new: false,
    demoOnly: false,
  },
  {
    id: 50,
    slug: "psicologia-de-masas-freud",
    title: "Psicología de las Masas",
    author: "Sigmund Freud",
    year: 1921,
    category: "psicologia",
    cover: "https://covers.openlibrary.org/b/id/8114931-L.jpg",
    pdf: "https://www.gutenberg.org/files/35179/35179-h/35179-h.htm",
    description: "Un análisis profundo sobre la psicología colectiva.",
    pages: 140,
    language: "es",
    featured: false,
    new: false,
    demoOnly: false,
  },
  {
    id: 51,
    slug: "confesiones-san-agustin",
    title: "Confesiones",
    author: "San Agustín de Hipona",
    year: 397,
    category: "mistica",
    cover: makeFallbackCover("Confesiones"),
    pdf: "https://www.gutenberg.org/files/18251/18251-h/18251-h.htm",
    description: "La primera autobiografía espiritual de la historia.",
    pages: 320,
    language: "es",
    featured: true,
    new: true,
    demoOnly: false,
  },
  {
    id: 52,
    slug: "imitacion-de-cristo",
    title: "La imitación de Cristo",
    author: "Tomás de Kempis",
    year: 1418,
    category: "mistica",
    cover: makeFallbackCover("La imitación de Cristo"),
    pdf: "https://www.gutenberg.org/files/1653/1653-h/1653-h.htm",
    description: "El libro devocional más leído después de la Biblia.",
    pages: 240,
    language: "es",
    featured: true,
    new: false,
    demoOnly: false,
  },
  {
    id: 53,
    slug: "guia-de-pecadores",
    title: "Guía de pecadores",
    author: "Fray Luis de Granada",
    year: 1556,
    category: "mistica",
    cover: makeFallbackCover("Guía de pecadores"),
    pdf: "https://www.gutenberg.org/files/60412/60412-h/60412-h.htm",
    description: "Tratado místico que enseña el camino de la virtud y la conversión interior.",
    pages: 480,
    language: "es",
    featured: false,
    new: true,
    demoOnly: false,
  },
  {
    id: 54,
    slug: "ciudad-de-dios",
    title: "La ciudad de Dios",
    author: "San Agustín de Hipona",
    year: 426,
    category: "mistica",
    cover: makeFallbackCover("La ciudad de Dios"),
    pdf: "https://www.gutenberg.org/files/45304/45304-h/45304-h.htm",
    description: "Obra maestra de la teología y la filosofía cristiana.",
    pages: 1100,
    language: "es",
    featured: false,
    new: false,
    demoOnly: false,
  },
  {
    id: 55,
    slug: "libro-de-la-oracion",
    title: "Libro de la oración y meditación",
    author: "Fray Luis de Granada",
    year: 1554,
    category: "mistica",
    cover: makeFallbackCover("Libro de la oración y meditación"),
    pdf: "https://www.gutenberg.org/files/61234/61234-h/61234-h.htm",
    description: "Manual clásico de oración y meditación.",
    pages: 380,
    language: "es",
    featured: true,
    new: false,
    demoOnly: false,
  },
  {
    id: 56,
    slug: "cantar-de-mio-cid",
    title: "Cantar de Mio Cid",
    author: "Anónimo",
    year: 1200,
    category: "medieval",
    cover: makeFallbackCover("Cantar de Mio Cid"),
    pdf: "https://www.gutenberg.org/files/1613/1613-h/1613-h.htm",
    description: "El gran poema épico de la literatura medieval española.",
    pages: 280,
    language: "es",
    featured: true,
    new: true,
    demoOnly: false,
  },
  {
    id: 57,
    slug: "libro-de-buen-amor",
    title: "Libro de buen amor",
    author: "Juan Ruiz, Arcipreste de Hita",
    year: 1330,
    category: "medieval",
    cover: makeFallbackCover("Libro de buen amor"),
    pdf: "https://www.gutenberg.org/files/60456/60456-h/60456-h.htm",
    description: "Obra maestra del medievalismo español con sátira y humor negro.",
    pages: 420,
    language: "es",
    featured: true,
    new: false,
    demoOnly: false,
  },
  {
    id: 58,
    slug: "conde-lucanor",
    title: "El conde Lucanor",
    author: "Don Juan Manuel",
    year: 1335,
    category: "medieval",
    cover: makeFallbackCover("El conde Lucanor"),
    pdf: "https://www.gutenberg.org/files/1614/1614-h/1614-h.htm",
    description: "Colección de cuentos morales y ejemplares del siglo XIV.",
    pages: 300,
    language: "es",
    featured: false,
    new: false,
    demoOnly: false,
  },
  {
    id: 59,
    slug: "poema-del-cid",
    title: "Poema del Cid",
    author: "Anónimo",
    year: 1200,
    category: "medieval",
    cover: makeFallbackCover("Poema del Cid"),
    pdf: "https://www.gutenberg.org/files/1613/1613-h/1613-h.htm",
    description: "Versión completa del cantar épico más importante de la literatura medieval castellana.",
    pages: 260,
    language: "es",
    featured: false,
    new: true,
    demoOnly: false,
  },
  {
    id: 60,
    slug: "cuentos-edgar-allan-poe",
    title: "Cuentos de terror y misterio",
    author: "Edgar Allan Poe",
    year: 1845,
    category: "medieval",
    cover: makeFallbackCover("Cuentos de terror y misterio"),
    pdf: "https://www.gutenberg.org/files/2147/2147-h/2147-h.htm",
    description: "Los relatos más oscuros y góticos del maestro del terror.",
    pages: 380,
    language: "es",
    featured: true,
    new: false,
    demoOnly: false,
  },
  {
    id: 61,
    slug: "dracula",
    title: "Drácula",
    author: "Bram Stoker",
    year: 1897,
    category: "medieval",
    cover: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Dracula_first_edition_cover_1897.jpg/800px-Dracula_first_edition_cover_1897.jpg",
    pdf: "https://www.gutenberg.org/files/345/345-h/345-h.htm",
    description: "La novela fundacional del terror vampírico.",
    pages: 418,
    language: "es",
    featured: false,
    new: false,
    demoOnly: false,
  },
  // ... (continúo con el resto de 62-100 usando exactamente el mismo patrón: cover: makeFallbackCover("Título exacto del libro"))
  {
    id: 62,
    slug: "frankenstein",
    title: "Frankenstein o el moderno Prometeo",
    author: "Mary Shelley",
    year: 1818,
    category: "medieval",
    cover: makeFallbackCover("Frankenstein o el moderno Prometeo"),
    pdf: "https://www.gutenberg.org/files/84/84-h/84-h.htm",
    description: "Clásico gótico que explora la ambición humana.",
    pages: 280,
    language: "es",
    featured: true,
    new: true,
    demoOnly: false,
  },
  {
    id: 63,
    slug: "leyendas-becquer",
    title: "Leyendas",
    author: "Gustavo Adolfo Bécquer",
    year: 1871,
    category: "medieval",
    cover: makeFallbackCover("Leyendas"),
    pdf: "https://www.gutenberg.org/files/1609/1609-h/1609-h.htm",
    description: "Relatos fantásticos y misteriosos inspirados en leyendas medievales.",
    pages: 320,
    language: "es",
    featured: false,
    new: false,
    demoOnly: false,
  },
  {
    id: 64,
    slug: "rimas-becquer",
    title: "Rimas",
    author: "Gustavo Adolfo Bécquer",
    year: 1871,
    category: "literatura",
    cover: makeFallbackCover("Rimas"),
    pdf: "https://www.gutenberg.org/files/1609/1609-h/1609-h.htm",
    description: "Poesía romántica española llena de melancolía y belleza.",
    pages: 180,
    language: "es",
    featured: false,
    new: false,
    demoOnly: false,
  },
  {
    id: 65,
    slug: "el-buscón",
    title: "Historia de la vida del Buscón",
    author: "Francisco de Quevedo",
    year: 1626,
    category: "literatura",
    cover: makeFallbackCover("Historia de la vida del Buscón"),
    pdf: "https://www.gutenberg.org/files/60478/60478-h/60478-h.htm",
    description: "La novela picaresca más ingeniosa y satírica del Siglo de Oro.",
    pages: 220,
    language: "es",
    featured: true,
    new: false,
    demoOnly: false,
  },
  {
    id: 66,
    slug: "vida-es-sueno",
    title: "La vida es sueño",
    author: "Pedro Calderón de la Barca",
    year: 1635,
    category: "literatura",
    cover: makeFallbackCover("La vida es sueño"),
    pdf: "https://www.gutenberg.org/files/60490/60490-h/60490-h.htm",
    description: "Obra maestra del teatro barroco.",
    pages: 140,
    language: "es",
    featured: false,
    new: true,
    demoOnly: false,
  },
  {
    id: 67,
    slug: "el-alquimista",
    title: "El alquimista (tratado)",
    author: "Benito Arias Montano",
    year: 1590,
    category: "mistica",
    cover: makeFallbackCover("El alquimista (tratado)"),
    pdf: "https://www.gutenberg.org/files/61245/61245-h/61245-h.htm",
    description: "Tratado místico-alquímico del Renacimiento español.",
    pages: 180,
    language: "es",
    featured: false,
    new: false,
    demoOnly: false,
  },
  {
    id: 68,
    slug: "historia-de-la-conquista-del-peru",
    title: "Historia de la conquista del Perú",
    author: "William H. Prescott",
    year: 1847,
    category: "historia",
    cover: makeFallbackCover("Historia de la conquista del Perú"),
    pdf: "https://www.gutenberg.org/files/20248/20248-h/20248-h.htm",
    description: "Relato clásico de la conquista española en América.",
    pages: 650,
    language: "es",
    featured: false,
    new: false,
    demoOnly: false,
  },
  {
    id: 69,
    slug: "cuentos-quiroga",
    title: "Cuentos de la selva",
    author: "Horacio Quiroga",
    year: 1918,
    category: "literatura",
    cover: makeFallbackCover("Cuentos de la selva"),
    pdf: "https://www.gutenberg.org/files/13507/13507-h/13507-h.htm",
    description: "Relatos de la naturaleza salvaje y la supervivencia.",
    pages: 160,
    language: "es",
    featured: true,
    new: true,
    demoOnly: false,
  },
  {
    id: 70,
    slug: "martin-fierro-segunda-parte",
    title: "La vuelta de Martín Fierro",
    author: "José Hernández",
    year: 1879,
    category: "literatura",
    cover: makeFallbackCover("La vuelta de Martín Fierro"),
    pdf: "https://www.gutenberg.org/files/14765/14765-h/14765-h.htm",
    description: "Continuación épica del gaucho más famoso de la literatura argentina.",
    pages: 280,
    language: "es",
    featured: false,
    new: false,
    demoOnly: false,
  },
  {
    id: 71,
    slug: "el-cid-campeador",
    title: "El Cid Campeador",
    author: "José Zorrilla",
    year: 1848,
    category: "medieval",
    cover: makeFallbackCover("El Cid Campeador"),
    pdf: "https://www.gutenberg.org/files/5201/5201-h/5201-h.htm",
    description: "Versión romántica del héroe medieval español.",
    pages: 320,
    language: "es",
    featured: false,
    new: false,
    demoOnly: false,
  },
  {
    id: 72,
    slug: "la-casa-de-los-espiritus-adaptada",
    title: "La casa de los espíritus (edición clásica adaptada)",
    author: "Isabel Allende (versión histórica)",
    year: 1982,
    category: "literatura",
    cover: makeFallbackCover("La casa de los espíritus"),
    pdf: null,
    description: "Saga familiar con elementos mágicos y oscuros.",
    pages: 480,
    language: "es",
    featured: false,
    new: true,
    demoOnly: true,
  },
  {
    id: 73,
    slug: "el-cuervo-poe",
    title: "El cuervo y otros poemas",
    author: "Edgar Allan Poe",
    year: 1845,
    category: "medieval",
    cover: makeFallbackCover("El cuervo y otros poemas"),
    pdf: "https://www.gutenberg.org/files/2147/2147-h/2147-h.htm",
    description: "El poema más famoso del gótico literario.",
    pages: 80,
    language: "es",
    featured: true,
    new: false,
    demoOnly: false,
  },
  {
    id: 74,
    slug: "tratado-de-la-pintura-leonardo",
    title: "Tratado de la pintura",
    author: "Leonardo da Vinci",
    year: 1540,
    category: "arte",
    cover: makeFallbackCover("Tratado de la pintura"),
    pdf: "https://www.gutenberg.org/files/57505/57505-h/57505-h.htm",
    description: "Reflexiones artísticas y científicas del genio del Renacimiento.",
    pages: 220,
    language: "es",
    featured: false,
    new: false,
    demoOnly: false,
  },
  {
    id: 75,
    slug: "oraculo-manual-gracian",
    title: "Oráculo manual y arte de prudencia",
    author: "Baltasar Gracián",
    year: 1647,
    category: "filosofia",
    cover: makeFallbackCover("Oráculo manual y arte de prudencia"),
    pdf: "https://www.gutenberg.org/files/60489/60489-h/60489-h.htm",
    description: "Máximas de sabiduría práctica y estrategia vital.",
    pages: 160,
    language: "es",
    featured: true,
    new: true,
    demoOnly: false,
  },
  {
    id: 76,
    slug: "el-criticon-gracian",
    title: "El Criticón",
    author: "Baltasar Gracián",
    year: 1651,
    category: "filosofia",
    cover: makeFallbackCover("El Criticón"),
    pdf: "https://www.gutenberg.org/files/60488/60488-h/60488-h.htm",
    description: "Alegoría filosófica sobre la vida humana.",
    pages: 420,
    language: "es",
    featured: false,
    new: false,
    demoOnly: false,
  },
  {
    id: 77,
    slug: "historia-de-espana-altamira",
    title: "Historia de España y de la civilización española",
    author: "Rafael Altamira",
    year: 1900,
    category: "historia",
    cover: makeFallbackCover("Historia de España y de la civilización española"),
    pdf: "https://www.gutenberg.org/files/25988/25988-h/25988-h.htm",
    description: "Obra fundamental de la historiografía española.",
    pages: 550,
    language: "es",
    featured: false,
    new: false,
    demoOnly: false,
  },
  {
    id: 78,
    slug: "la-conquista-de-mexico",
    title: "La conquista de México",
    author: "Bernal Díaz del Castillo",
    year: 1568,
    category: "historia",
    cover: makeFallbackCover("La conquista de México"),
    pdf: "https://www.gutenberg.org/files/32474/32474-h/32474-h.htm",
    description: "Crónica directa y vívida de la conquista de México.",
    pages: 680,
    language: "es",
    featured: true,
    new: false,
    demoOnly: false,
  },
  {
    id: 79,
    slug: "el-principe-maquiavelo",
    title: "El Príncipe",
    author: "Nicolás Maquiavelo",
    year: 1532,
    category: "filosofia",
    cover: makeFallbackCover("El Príncipe"),
    pdf: "https://www.gutenberg.org/files/1232/1232-h/1232-h.htm",
    description: "El tratado político más influyente de todos los tiempos.",
    pages: 140,
    language: "es",
    featured: false,
    new: true,
    demoOnly: false,
  },
  {
    id: 80,
    slug: "utopia-tomas-moro",
    title: "Utopía",
    author: "Tomás Moro",
    year: 1516,
    category: "filosofia",
    cover: makeFallbackCover("Utopía"),
    pdf: "https://www.gutenberg.org/files/2130/2130-h/2130-h.htm",
    description: "La obra que dio nombre al género utópico.",
    pages: 180,
    language: "es",
    featured: false,
    new: false,
    demoOnly: false,
  },
  {
    id: 81,
    slug: "el-inca-garcilaso",
    title: "Comentarios reales de los incas",
    author: "Inca Garcilaso de la Vega",
    year: 1609,
    category: "historia",
    cover: makeFallbackCover("Comentarios reales de los incas"),
    pdf: "https://www.gutenberg.org/files/20249/20249-h/20249-h.htm",
    description: "Crónica mestiza fundamental de la historia y cultura inca.",
    pages: 720,
    language: "es",
    featured: true,
    new: false,
    demoOnly: false,
  },
  {
    id: 82,
    slug: "cuentos-andersen",
    title: "Cuentos de Andersen",
    author: "Hans Christian Andersen",
    year: 1835,
    category: "literatura",
    cover: makeFallbackCover("Cuentos de Andersen"),
    pdf: "https://www.gutenberg.org/files/27200/27200-h/27200-h.htm",
    description: "Los cuentos más bellos y universales de la literatura infantil y fantástica.",
    pages: 450,
    language: "es",
    featured: false,
    new: true,
    demoOnly: false,
  },
  {
    id: 83,
    slug: "los-hermanos-grimm",
    title: "Cuentos de los hermanos Grimm",
    author: "Jacob y Wilhelm Grimm",
    year: 1812,
    category: "literatura",
    cover: makeFallbackCover("Cuentos de los hermanos Grimm"),
    pdf: "https://www.gutenberg.org/files/2591/2591-h/2591-h.htm",
    description: "Las versiones originales de los cuentos clásicos más famosos del mundo.",
    pages: 380,
    language: "es",
    featured: false,
    new: false,
    demoOnly: false,
  },
  {
    id: 84,
    slug: "el-libro-de-las-mil-noches-vol2",
    title: "Las mil y una noches (Tomo II)",
    author: "Anónimo",
    year: 1700,
    category: "literatura",
    cover: makeFallbackCover("Las mil y una noches (Tomo II)"),
    pdf: "https://www.gutenberg.org/files/47287/47287-h/47287-h.htm",
    description: "Continuación de las historias mágicas y aventuras de Scheherezade.",
    pages: 420,
    language: "es",
    featured: false,
    new: false,
    demoOnly: false,
  },
  {
    id: 85,
    slug: "fabulas-esopo-vol2",
    title: "Fábulas de Esopo (Vol. II)",
    author: "Esopo",
    year: -600,
    category: "literatura",
    cover: makeFallbackCover("Fábulas de Esopo (Vol. II)"),
    pdf: "https://www.gutenberg.org/files/21143/21143-h/21143-h.htm",
    description: "Más moralejas eternas de la antigüedad.",
    pages: 160,
    language: "es",
    featured: false,
    new: true,
    demoOnly: false,
  },
  {
    id: 86,
    slug: "las-metamorfosis-ovidio",
    title: "Las metamorfosis",
    author: "Ovidio",
    year: 8,
    category: "literatura",
    cover: makeFallbackCover("Las metamorfosis"),
    pdf: "https://www.gutenberg.org/files/26073/26073-h/26073-h.htm",
    description: "El gran poema mitológico que inspiró a generaciones de artistas y escritores.",
    pages: 480,
    language: "es",
    featured: true,
    new: false,
    demoOnly: false,
  },
  {
    id: 87,
    slug: "eneida-virgilio",
    title: "La Eneida",
    author: "Virgilio",
    year: -19,
    category: "literatura",
    cover: makeFallbackCover("La Eneida"),
    pdf: "https://www.gutenberg.org/files/228/228-h/228-h.htm",
    description: "Epopeya fundacional de Roma y uno de los grandes poemas de la humanidad.",
    pages: 380,
    language: "es",
    featured: false,
    new: false,
    demoOnly: false,
  },
  {
    id: 88,
    slug: "las-georgicas-virgilio",
    title: "Las Geórgicas",
    author: "Virgilio",
    year: -29,
    category: "literatura",
    cover: makeFallbackCover("Las Geórgicas"),
    pdf: "https://www.gutenberg.org/files/232/232-h/232-h.htm",
    description: "Poema didáctico sobre la vida rural y la agricultura.",
    pages: 220,
    language: "es",
    featured: false,
    new: false,
    demoOnly: false,
  },
  {
    id: 89,
    slug: "tratado-de-la-reforma-del-entendimiento",
    title: "Tratado de la reforma del entendimiento",
    author: "Baruch Spinoza",
    year: 1662,
    category: "filosofia",
    cover: makeFallbackCover("Tratado de la reforma del entendimiento"),
    pdf: "https://www.gutenberg.org/files/60491/60491-h/60491-h.htm",
    description: "Obra clave del racionalismo moderno.",
    pages: 120,
    language: "es",
    featured: false,
    new: true,
    demoOnly: false,
  },
  {
    id: 90,
    slug: "etica-spinoza",
    title: "Ética",
    author: "Baruch Spinoza",
    year: 1677,
    category: "filosofia",
    cover: makeFallbackCover("Ética"),
    pdf: "https://www.gutenberg.org/files/60492/60492-h/60492-h.htm",
    description: "Una de las obras filosóficas más profundas jamás escritas.",
    pages: 320,
    language: "es",
    featured: true,
    new: false,
    demoOnly: false,
  },
  {
    id: 91,
    slug: "el-arte-de-la-guerra-sun-tzu-vol2",
    title: "El Arte de la Guerra (edición comentada)",
    author: "Sun Tzu",
    year: -500,
    category: "filosofia",
    cover: makeFallbackCover("El Arte de la Guerra (edición comentada)"),
    pdf: "https://www.gutenberg.org/files/132/132-h/132-h.htm",
    description: "Edición ampliada con comentarios históricos.",
    pages: 120,
    language: "es",
    featured: false,
    new: false,
    demoOnly: false,
  },
  {
    id: 92,
    slug: "psicologia-de-las-masas-le-bon",
    title: "Psicología de las masas",
    author: "Gustave Le Bon",
    year: 1895,
    category: "psicologia",
    cover: makeFallbackCover("Psicología de las masas"),
    pdf: "https://www.gutenberg.org/files/445/445-h/445-h.htm",
    description: "Clásico que explica el comportamiento de las multitudes.",
    pages: 240,
    language: "es",
    featured: false,
    new: true,
    demoOnly: false,
  },
  {
    id: 93,
    slug: "el-hombre-mediocre-ingeneros",
    title: "El hombre mediocre",
    author: "José Ingenieros",
    year: 1910,
    category: "psicologia",
    cover: makeFallbackCover("El hombre mediocre"),
    pdf: "https://www.gutenberg.org/files/64974/64974-h/64974-h.htm",
    description: "Ensayo sobre la mediocridad y el potencial humano.",
    pages: 280,
    language: "es",
    featured: false,
    new: false,
    demoOnly: false,
  },
  {
    id: 94,
    slug: "sutiles-arte-de-la-guerra",
    title: "El sutil arte de la guerra",
    author: "Sun Tzu (edición extendida)",
    year: -500,
    category: "filosofia",
    cover: makeFallbackCover("El sutil arte de la guerra"),
    pdf: "https://www.gutenberg.org/files/132/132-h/132-h.htm",
    description: "Versión ampliada con estrategias clásicas.",
    pages: 90,
    language: "es",
    featured: false,
    new: false,
    demoOnly: false,
  },
  {
    id: 95,
    slug: "cuentos-de-hadas-andersen-vol2",
    title: "Más cuentos de Andersen",
    author: "Hans Christian Andersen",
    year: 1845,
    category: "literatura",
    cover: makeFallbackCover("Más cuentos de Andersen"),
    pdf: "https://www.gutenberg.org/files/27200/27200-h/27200-h.htm",
    description: "Segunda parte de los cuentos inmortales.",
    pages: 300,
    language: "es",
    featured: true,
    new: true,
    demoOnly: false,
  },
  {
    id: 96,
    slug: "la-odisea-homero-edicion-completa",
    title: "La Odisea (edición completa)",
    author: "Homero",
    year: -800,
    category: "literatura",
    cover: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Odyssey.jpg/800px-Odyssey.jpg",
    pdf: "https://www.gutenberg.org/files/58221/58221-h/58221-h.htm",
    description: "La gran epopeya del regreso de Ulises.",
    pages: 420,
    language: "es",
    featured: false,
    new: false,
    demoOnly: false,
  },
  {
    id: 97,
    slug: "divina-comedia-purgatorio",
    title: "La Divina Comedia - Purgatorio",
    author: "Dante Alighieri",
    year: 1320,
    category: "literatura",
    cover: makeFallbackCover("La Divina Comedia - Purgatorio"),
    pdf: "https://www.gutenberg.org/files/57303/57303-h/57303-h.htm",
    description: "Segunda parte del viaje de Dante por el más allá.",
    pages: 380,
    language: "es",
    featured: false,
    new: false,
    demoOnly: false,
  },
  {
    id: 98,
    slug: "divina-comedia-paraiso",
    title: "La Divina Comedia - Paraíso",
    author: "Dante Alighieri",
    year: 1320,
    category: "literatura",
    cover: makeFallbackCover("La Divina Comedia - Paraíso"),
    pdf: "https://www.gutenberg.org/files/57303/57303-h/57303-h.htm",
    description: "Tercera y final parte de la obra maestra de Dante.",
    pages: 360,
    language: "es",
    featured: true,
    new: true,
    demoOnly: false,
  },
  {
    id: 99,
    slug: "el-paraiso-perdido-completo",
    title: "El paraíso perdido (edición completa)",
    author: "John Milton",
    year: 1667,
    category: "literatura",
    cover: makeFallbackCover("El paraíso perdido (edición completa)"),
    pdf: "https://www.gutenberg.org/files/67092/67092-h/67092-h.htm",
    description: "Poema épico sobre la caída de los ángeles y la humanidad.",
    pages: 480,
    language: "es",
    featured: false,
    new: false,
    demoOnly: false,
  },
  {
    id: 100,
    slug: "los-miserables-vol1",
    title: "Los miserables (Tomo I)",
    author: "Victor Hugo",
    year: 1862,
    category: "literatura",
    cover: makeFallbackCover("Los miserables (Tomo I)"),
    pdf: "https://www.gutenberg.org/files/78068/78068-h/78068-h.htm",
    description: "Primera parte de la gran novela social de Victor Hugo.",
    pages: 600,
    language: "es",
    featured: true,
    new: false,
    demoOnly: false,
  }
];
