// ============================================================
//  data.js  –  Catálogo de LibroVivo
// ============================================================

const CATEGORIES = [
  { id: "literatura",  label: "Literatura",  icon: "fas fa-feather-alt" },
  { id: "ciencia",     label: "Ciencia",     icon: "fas fa-flask" },
  { id: "filosofia",   label: "Filosofía",   icon: "fas fa-brain" },
  { id: "historia",    label: "Historia",    icon: "fas fa-landmark" },
  { id: "tecnologia",  label: "Tecnología",  icon: "fas fa-microchip" },
  { id: "arte",        label: "Arte",        icon: "fas fa-palette" },
  { id: "economia",    label: "Economía",    icon: "fas fa-chart-line" },
  { id: "psicologia",  label: "Psicología",  icon: "fas fa-head-side-virus" },
];

// Fallback SVG cover generator (data URI) – no external dependency
function makeFallbackCover(title, color1 = '#6B1E2B', color2 = '#C9973A') {
  const t = encodeURIComponent(title.slice(0, 20));
  return `data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='300' height='450'%3E%3Cdefs%3E%3ClinearGradient id='g' x1='0' y1='0' x2='1' y2='1'%3E%3Cstop offset='0' stop-color='${encodeURIComponent(color1)}'/%3E%3Cstop offset='1' stop-color='${encodeURIComponent(color2)}'/%3E%3C/linearGradient%3E%3C/defs%3E%3Crect width='300' height='450' fill='url(%23g)'/%3E%3Crect x='20' y='20' width='260' height='410' fill='none' stroke='rgba(255,255,255,.2)' stroke-width='1'/%3E%3Ctext x='150' y='200' text-anchor='middle' font-family='serif' font-size='60' fill='rgba(255,255,255,.15)'%3E%F0%9F%93%96%3C/text%3E%3C/svg%3E`;
}

const BOOKS = [
  {
    id: 1,
    slug: "el-principito",
    title: "El Principito",
    author: "Antoine de Saint-Exupéry",
    year: 1943,
    category: "literatura",
    cover: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/Le_Petit_Prince_de_Saint-Exup%C3%A9ry_%281943%29.jpg/800px-Le_Petit_Prince_de_Saint-Exup%C3%A9ry_%281943%29.jpg",
    // Public domain PDF via wikimedia / direct embed
    pdf: "https://www.gutenberg.org/files/10716/10716-h/10716-h.htm",
    pdfEmbed: "https://docs.google.com/viewer?url=https%3A%2F%2Fwww.planetadelibros.com%2Fusuaris%2Flibros%2Ffotos%2F28%2Fm_libros%2F28684_el-principito.pdf&embedded=true",
    description: "Un clásico atemporal que narra el viaje de un pequeño príncipe por diferentes planetas, donde conoce personajes que representan la soledad, la vanidad y el amor.",
    pages: 96,
    language: "es",
    featured: true,
    new: true,
    demoOnly: false,
  },
  {
    id: 2,
    slug: "don-quijote",
    title: "Don Quijote de la Mancha",
    author: "Miguel de Cervantes",
    year: 1605,
    category: "literatura",
    cover: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2b/Cervantes_Quijote.jpg/800px-Cervantes_Quijote.jpg",
    pdf: "https://www.gutenberg.org/files/2000/2000-h/2000-h.htm",
    description: "La novela más influyente de la lengua española y una de las obras literarias más importantes del mundo. Narra las aventuras del ingenioso hidalgo Alonso Quijano.",
    pages: 1008,
    language: "es",
    featured: true,
    new: false,
    demoOnly: false,
  },
  {
    id: 3,
    slug: "cosmos-sagan",
    title: "Cosmos",
    author: "Carl Sagan",
    year: 1980,
    category: "ciencia",
    cover: "https://upload.wikimedia.org/wikipedia/en/thumb/6/61/Cosmos_by_carl_sagan.jpg/220px-Cosmos_by_carl_sagan.jpg",
    pdf: null,
    description: "Un viaje fascinante por el universo, desde el origen del cosmos hasta el futuro de la humanidad, escrito por uno de los más grandes divulgadores científicos.",
    pages: 365,
    language: "es",
    featured: true,
    new: false,
    demoOnly: true,
  },
  {
    id: 4,
    slug: "mas-platon-menos-prozac",
    title: "Más Platón y Menos Prozac",
    author: "Lou Marinoff",
    year: 1999,
    category: "filosofia",
    cover: "https://covers.openlibrary.org/b/id/8222463-L.jpg",
    pdf: null,
    description: "Una obra que propone aplicar la sabiduría de los grandes filósofos de la historia para resolver los problemas cotidianos del hombre moderno.",
    pages: 352,
    language: "es",
    featured: false,
    new: true,
    demoOnly: true,
  },
  {
    id: 5,
    slug: "sapiens",
    title: "Sapiens: De Animales a Dioses",
    author: "Yuval Noah Harari",
    year: 2011,
    category: "historia",
    cover: "https://upload.wikimedia.org/wikipedia/en/thumb/0/06/Sapiens_A_Brief_History_of_Humankind.jpg/220px-Sapiens_A_Brief_History_of_Humankind.jpg",
    pdf: null,
    description: "Una breve historia de la humanidad que explora cómo Homo sapiens llegó a dominar la Tierra, desde la prehistoria hasta el presente.",
    pages: 496,
    language: "es",
    featured: true,
    new: true,
    demoOnly: true,
  },
  {
    id: 6,
    slug: "inteligencia-artificial-russel",
    title: "Inteligencia Artificial: Un Enfoque Moderno",
    author: "Stuart Russell & Peter Norvig",
    year: 2010,
    category: "tecnologia",
    cover: "https://covers.openlibrary.org/b/id/8091016-L.jpg",
    pdf: null,
    description: "El texto de referencia más utilizado en cursos de inteligencia artificial en el mundo. Cubre desde búsqueda y planificación hasta aprendizaje automático.",
    pages: 1132,
    language: "es",
    featured: true,
    new: false,
    demoOnly: true,
  },
  {
    id: 7,
    slug: "el-arte-de-la-guerra",
    title: "El Arte de la Guerra",
    author: "Sun Tzu",
    year: -500,
    category: "filosofia",
    cover: "https://covers.openlibrary.org/b/id/8235423-L.jpg",
    // Gutenberg public domain
    pdf: "https://www.gutenberg.org/files/132/132-h/132-h.htm",
    description: "El tratado militar más antiguo del mundo, con profundas reflexiones sobre estrategia, liderazgo y la naturaleza del conflicto que trascienden lo militar.",
    pages: 68,
    language: "es",
    featured: false,
    new: false,
    demoOnly: false,
  },
  {
    id: 8,
    slug: "padre-rico-padre-pobre",
    title: "Padre Rico, Padre Pobre",
    author: "Robert T. Kiyosaki",
    year: 1997,
    category: "economia",
    cover: "https://covers.openlibrary.org/b/id/8395468-L.jpg",
    pdf: null,
    description: "El libro de finanzas personales más vendido de todos los tiempos. Enseña la diferencia entre trabajar por dinero y hacer que el dinero trabaje para ti.",
    pages: 207,
    language: "es",
    featured: false,
    new: true,
    demoOnly: true,
  },
  {
    id: 9,
    slug: "psicologia-de-masas",
    title: "Psicología de las Masas",
    author: "Sigmund Freud",
    year: 1921,
    category: "psicologia",
    cover: "https://covers.openlibrary.org/b/id/8114931-L.jpg",
    // Gutenberg public domain
    pdf: "https://www.gutenberg.org/files/35179/35179-h/35179-h.htm",
    description: "Un análisis profundo sobre la psicología colectiva y cómo los individuos se comportan cuando forman parte de grupos, multitudes e instituciones.",
    pages: 140,
    language: "es",
    featured: false,
    new: false,
    demoOnly: false,
  },
  {
    id: 10,
    slug: "historia-del-arte-gombrich",
    title: "La Historia del Arte",
    author: "E.H. Gombrich",
    year: 1950,
    category: "arte",
    cover: "https://covers.openlibrary.org/b/id/8231996-L.jpg",
    pdf: null,
    description: "Considerado el mejor libro introductorio al arte de todos los tiempos. Recorre la historia del arte desde las pinturas rupestres hasta el arte del siglo XX.",
    pages: 688,
    language: "es",
    featured: true,
    new: true,
    demoOnly: true,
  },
  {
    id: 11,
    slug: "cien-anos-soledad",
    title: "Cien Años de Soledad",
    author: "Gabriel García Márquez",
    year: 1967,
    category: "literatura",
    cover: "https://upload.wikimedia.org/wikipedia/en/thumb/f/f4/CienAnosDeSoledad.jpg/220px-CienAnosDeSoledad.jpg",
    pdf: null,
    description: "La obra cumbre del realismo mágico y una de las novelas más importantes del siglo XX. Narra la historia de la familia Buendía a lo largo de siete generaciones.",
    pages: 432,
    language: "es",
    featured: true,
    new: false,
    demoOnly: true,
  },
  {
    id: 12,
    slug: "breve-historia-del-tiempo",
    title: "Breve Historia del Tiempo",
    author: "Stephen Hawking",
    year: 1988,
    category: "ciencia",
    cover: "https://upload.wikimedia.org/wikipedia/en/thumb/a/a3/BriefHistoryOfTime.jpg/220px-BriefHistoryOfTime.jpg",
    pdf: null,
    description: "Una exploración accesible de los conceptos más complejos de la física moderna: el Big Bang, los agujeros negros, el tiempo y el universo.",
    pages: 212,
    language: "es",
    featured: false,
    new: true,
    demoOnly: true,
  },
];
